<#
.SYNOPSIS
  Creates the Azure resources Harmony needs and prints a container SAS URL.

.DESCRIPTION
  Resource group -> StorageV2 account (Standard_LRS, TLS 1.2, no public blob
  access) -> private container -> long-lived container SAS with
  read/add/create/write/delete/list permissions.

  Requires the Azure CLI, already logged in (`az login`) with the right
  subscription selected.

.EXAMPLE
  ./scripts/azure-setup.ps1 -WriteEnv
  Creates everything with defaults and writes ./.env for you.

.EXAMPLE
  ./scripts/azure-setup.ps1 -AccountName stharmonyabc123 -Expiry 2032-01-01
#>
param(
  [string]$ResourceGroup = "rg-harmony",
  [string]$Location = "eastus2",
  [string]$AccountName = "",
  [string]$Container = "harmony",
  [string]$Expiry = "2031-01-01",
  [switch]$WriteEnv
)

$ErrorActionPreference = "Stop"

if (-not $AccountName) {
  $suffix = -join ((48..57) + (97..122) | Get-Random -Count 6 | ForEach-Object { [char]$_ })
  $AccountName = "stharmony$suffix"
}

Write-Host "Resource group  : $ResourceGroup ($Location)"
Write-Host "Storage account : $AccountName"
Write-Host "Container       : $Container"
Write-Host "SAS expiry      : $Expiry"
Write-Host ""

az group create --name $ResourceGroup --location $Location --output none
Write-Host "resource group ready"

az storage account create `
  --name $AccountName `
  --resource-group $ResourceGroup `
  --location $Location `
  --sku Standard_LRS `
  --kind StorageV2 `
  --access-tier Hot `
  --min-tls-version TLS1_2 `
  --allow-blob-public-access false `
  --output none
Write-Host "storage account ready"

$key = az storage account keys list --account-name $AccountName --resource-group $ResourceGroup --query "[0].value" --output tsv
if (-not $key) { throw "could not read the storage account key" }

az storage container create --name $Container --account-name $AccountName --account-key $key --output none
Write-Host "container ready"

$sas = az storage container generate-sas `
  --name $Container `
  --account-name $AccountName `
  --account-key $key `
  --permissions racwdl `
  --expiry $Expiry `
  --https-only `
  --output tsv
if (-not $sas) { throw "could not generate the SAS token" }

$url = "https://$AccountName.blob.core.windows.net/$Container`?$sas"
$line = "HARMONY_STORAGE=sas:$url"

Write-Host ""
if ($WriteEnv) {
  $envPath = Join-Path $PSScriptRoot ".." ".env"
  @(
    "# Generated by scripts/azure-setup.ps1 on $(Get-Date -Format s). Keep this file private.",
    $line,
    "HARMONY_BIND=127.0.0.1:8080",
    "RUST_LOG=harmony=info,tower_http=info"
  ) | Set-Content -Path $envPath -Encoding utf8
  Write-Host "wrote $((Resolve-Path $envPath).Path)"
} else {
  Write-Host "Add this to your .env:"
  Write-Host ""
  Write-Host $line
}
